# Copyright 2025 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Dict, List

class CompiledModelWrapper:
    def GetSignatureList(self) -> Dict[str, Dict[str, List[str]]]: ...
    def GetSignatureByIndex(self, index: int) -> Dict[str, Any]: ...

    def GetNumSignatures(self) -> int: ...

    def GetSignatureIndex(self, key: str) -> int: ...

    def GetInputBufferRequirements(self, sig_idx: int, in_idx: int) -> Dict[str, Any]: ...

    def GetOutputBufferRequirements(self, sig_idx: int, out_idx: int) -> Dict[str, Any]: ...
    def CreateInputBufferByName(self, sig_key: str, in_name: str) -> object: ...
    def CreateOutputBufferByName(self, sig_key: str, out_name: str) -> object: ...

    def CreateInputBuffers(self, sig_idx: int) -> List[object]: ...

    def CreateOutputBuffers(self, sig_idx: int) -> List[object]: ...
    def RunByName(self, sig_key: str, input_map: Dict[str, object], output_map: Dict[str, object]) -> None: ...

    def RunByIndex(self, sig_idx: int, input_caps_list: List[object], output_caps_list: List[object]) -> None: ...

    # New data I/O methods:
    def WriteFloatTensor(self, tensor_buffer_capsule: object, float_list: List[float]) -> None: ...

    def ReadFloatTensor(self, tensor_buffer_capsule: object, num_floats: int) -> List[float]: ...

    def DestroyTensorBuffer(self, tensor_buffer_capsule: object) -> None: ...

    def WriteTensor(self, tensor_buffer_capsule: object, data: list, dtype: str) -> None: ...

    def ReadTensor(self, tensor_buffer_capsule: object, num_elements: int, dtype: str) -> list: ...

    def CreateTensorBufferFromMemory(
            self, signature_key: str, tensor_name: str, data: Any, dtype: str
    ) -> object: ...

def CreateCompiledModelFromFile(
        model_path: str,
        compiler_plugin_path: str = ...,
        dispatch_library_path: str = ...,
        hardware_accel: int = ...
) -> CompiledModelWrapper: ...

def CreateCompiledModelFromBuffer(
        model_data: bytes,
        compiler_plugin_path: str = ...,
        dispatch_library_path: str = ...,
        hardware_accel: int = ...
) -> CompiledModelWrapper: ...
